[mypy]
plugins =
    mypy_django_plugin.main

python_version = 3.12
show_error_codes = True
warn_unused_ignores = True
check_untyped_defs = True

[mypy.plugins.django-stubs]
django_settings_module = "profcalendar.settings.dev"

[mypy-environ.*]
ignore_missing_imports = True