# Generated by Django 6.0.6 on 2026-06-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='exemple@exemple.com', max_length=254),
            preserve_default=False,
        ),
    ]
