# Generated by Django 6.0.6 on 2026-07-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_student_level_alter_student_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
    ]
