# Generated by Django 6.0.6 on 2026-07-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_student_level_remove_student_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='subect',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
