# Generated by Django 6.0.6 on 2026-07-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_student_level_student_subect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subect',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
