# Generated by Django 6.0.6 on 2026-07-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_student_subect_student_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='short',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='short',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
