# Generated by Django 6.0.6 on 2026-07-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_student_slug_alter_professor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
