# Generated by Django 6.0.6 on 2026-07-04 12:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_student_slug'),
    ]

    operations = []
