# Generated by Django 6.0.6 on 2026-07-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_lesson_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='commment',
            new_name='comment',
        ),
    ]
