# Generated by Django 6.0.6 on 2026-07-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_commment_lesson_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='commment',
            new_name='comment',
        ),
    ]
